# Generated by Django 3.1.6 on 2021-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211019_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default='assets\\img\\home\x08ed.png', null=True, upload_to='uploads/'),
        ),
    ]
