# Generated by Django 3.1.6 on 2021-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211019_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, default='assets\\img\\home\x08ed.png', null=True, upload_to='uploads/'),
        ),
    ]
