# Generated by Django 3.1.6 on 2021-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211018_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Confirm', 'Confirm'), ('Vendor recivied', 'Vendor recivied the order'), ('Ready to deliver', 'Ready to deliver'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
